### ISSUE TITLE
Deployment umstellen

### ISSUE THREAD

**Issue by InverseIntegral** [altcomphsr/altcomphsr.vshsr.ch#78]
Das momentane Deployment mittels Travis CI funktioniert nicht mehr.
Lokal ist ein Deployment mittels `make deploy` möglich, nur auf dem Buildserver schlägt das Deployen fehl..

Nach einigen Stunden probieren, bin ich auf folgende Issues gestossen:

- https://github.com/travis-ci/travis-ci/issues/9391
- https://github.com/travis-ci/travis-ci/issues/9529

Leider gibt es von Travis CI noch keine Neuigkeiten, wie man das Problem beheben kann.
Eine Option wäre die Webseite [direkt auf GitHub](https://help.github.com/articles/about-github-pages-and-jekyll/) zu hosten.

**Comment by The-Compiler** [comment]
Ist der Server nur via FTP erreichbar, oder auch z.B. via SFTP (via SSH)?

**Comment by InverseIntegral** [comment]
Soviel ich weiss, ist der Server nur über FTPS erreichbar. Mit SFTP konnte ich mich nicht verbinden.

**Comment by raphiz** [comment]
Ja, via SSH geht soweit ich weiss nicht, sonst hätten wir das bereits damals so gelöst

GitHub Pages bietet sich mittlerweile auch an, da erst seit relativ kurzem TLS auch mit eigenen Domains funzt. Zudem kann [TravisCI direkt GitHub Pages deployen](https://docs.travis-ci.com/user/deployment/pages/) was nicht so ein gefrickel wie mit ftp ist...

**Comment by InverseIntegral** [comment]
Wenn ich das richtig verstanden habe, würde die Seite dann nicht mehr in einem Docker-Container gebuildet & deployt werden. Ich habe das Ganze mal mit den GitHub Pages ausprobiert und folgendes travis.yml scheint zu funktionieren:

```
language: ruby

script:
  - mkdir _site/
  - chmod 777 _site/
  - jekyll build --destination _site

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
```
